export const USER_REPOSITORY = 'USER_REPOSITORY';
export const CREATOR_REPOSITORY = 'CREATOR_REPOSITORY';
export const PORTFOLIO_REPOSITORY = 'PORTFOLIO_REPOSITORY';
export const BRIEF_REPOSITORY = 'BRIEF_REPOSITORY';
export const SKILL_REPOSITORY = 'SKILL_REPOSITORY';
export const TOOL_REPOSITORY = 'TOOL_REPOSITORY';
export const VERIFICATION_REPOSITORY = 'VERIFICATION_REPOSITORY';
